version: '3.10'

services:
  db:
    image: postgres:latest
    volumes:
      - ./pg_volume_do_not_delete:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: atlius
      POSTGRES_USER: user_i
      POSTGRES_PASSWORD: pass

    ports:
      - "5432:5432"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
